# Generated by Django 5.2.3 on 2025-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='person name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='contact_images/', verbose_name='image')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
