# Generated by Django 5.2.3 on 2025-06-22 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('Masala', 'Masala Chai'), ('Ginger', 'Ginger Chai'), ('Cardamom', 'Cardamom Chai'), ('Lemon', 'Lemon Chai'), ('Plain', 'Plain Chai')], default='Plain', max_length=20),
        ),
    ]
