# Generated by Django 5.2.3 on 2025-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0002_chaivarity_date_added_chaivarity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
