# Generated by Django 5.2.3 on 2025-06-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0003_chaivarity_description_chaivarity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
